"""login_throttles

Revision ID: a58da83f8591
Revises: 0002_audit_immutability
"""

import sqlalchemy as sa
from alembic import op

revision = "a58da83f8591"
down_revision = "0002_audit_immutability"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_throttles",
        sa.Column("subject_hash", sa.String(length=64), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("attempts > 0", name=op.f("ck_login_throttles_positive_attempts")),
        sa.PrimaryKeyConstraint("subject_hash", name=op.f("pk_login_throttles")),
    )
    op.create_index(
        op.f("ix_login_throttles_window_start"), "login_throttles", ["window_start"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_login_throttles_window_start"), table_name="login_throttles")
    op.drop_table("login_throttles")
    # ### end Alembic commands ###
